### ISSUE TITLE
packageName-dev esy.json

### ISSUE THREAD

**Issue by idkjs** [chattyzilla-labs/zillaml#1]
I am studying your project and noted that in `note-cd`:
https://github.com/dakotamurphyucf/zillaml/blob/7dba5c343ba0f5432dac80e52e66bdcba17a3e09/package.json#L6-L12

It says we should create a `packageName-dev esy.json` file. I don't see a file fitting that description in this repo. Is the file necessary?

Thanks and thanks for sharing this project.

**Comment by dakotamurphyucf** [comment]
Hey!  For cloning the repo and building locally it is not. This project is still in it's infancy stage, and it is just preparation for when the project is ready to be published to npm.
